services:
  app:
  # 👇 Pull from ECR instead of local build
    image: ${IMAGE_URI:-110425445190.dkr.ecr.us-east-1.amazonaws.com/devops-training-portal:latest}
    container_name: portal-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}


