services:

  mysql:
    image: mysql:8.0
    container_name: portal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devops_portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: Portal@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: devops-training-portal:latest
    container_name: portal-app
    depends_on: 
       mysql:
         condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops_portal
      SPRING_DATASOURCE_USERNAME: portal_user
      SPRING_DATASOURCE_PASSWORD: Portal@123

volumes:
  mysql_data:


