spring.application.name=devops-training-portal
spring.datasource.url=jdbc:mysql://localhost:3306/devops_portal
spring.datasource.username=portal_user
spring.datasource.password=Portal@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false