spring.application.name=devops-training-portal

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devops_portal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:portal_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Portal@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false